name: Ruby

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Instalar ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Step 2 Install dependencies
      run: bundle install
    - name: Step 3 Run tests
      run: cucumber
    - name: Step 4 Archive production artifacts
      uses: actions/upload-artifact@v3
      if: ${{  always() }}
      with: 
        name: report
        path: ./reports/report.html
