name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: INSTALAR RUBY
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Step 2 Install dependencies
      run: bundle install
    - name: Step 3 Run tests
      run: cucumber
    - name: Step 4 Archive production artifacts
      uses: action/upload-artifacts@v3
      if: ${{  always() }}
      with: 
        name: report
        path: ./reports/report.html
